# Generated by Django 3.1.7 on 2021-05-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonsWealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tinkoff_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
