# Generated by Django 3.1.7 on 2021-05-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DragonsWealth', '0004_auto_20210508_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
